(()=>{"use strict";
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const header=q("[data-header]"); const progress=q("[data-progress]");
const onScroll=()=>{const y=scrollY;header?.classList.toggle("scrolled",y>30);if(progress){const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h?y/h*100:0)+"%"}};addEventListener("scroll",onScroll,{passive:true});onScroll();
const menu=q("[data-menu]");menu?.addEventListener("click",()=>{const open=header.classList.toggle("menu-open");menu.setAttribute("aria-expanded",String(open));});
qa(".nav a").forEach(a=>{if(a.href===location.href)a.classList.add("active")});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12});qa(".reveal").forEach(e=>observer.observe(e));
const cursor=q("[data-cursor]");if(cursor&&matchMedia("(pointer:fine)").matches){addEventListener("pointermove",e=>{cursor.style.left=e.clientX+"px";cursor.style.top=e.clientY+"px"})}
qa(".library-card").forEach((card,i)=>card.style.transitionDelay=Math.min(i%3*45,90)+"ms");
const filterButtons=qa("[data-filter]"),items=qa("[data-filter-item]"),count=q("[data-count]");
function filter(value){let n=0;items.forEach(item=>{const show=value==="all"||item.dataset.filterItem.split(" ").includes(value);item.hidden=!show;if(show)n++});if(count)count.textContent=n+" материалов";filterButtons.forEach(b=>b.classList.toggle("active",b.dataset.filter===value))}
if(filterButtons.length){filter("all");filterButtons.forEach(b=>b.addEventListener("click",()=>filter(b.dataset.filter)))}
})();
// Legacy interactive modules kept for biography/ideas/chronology pages.
const modalData={freedom:{title:"Свобода",body:"<p>У Достоевского свобода связана с ответственностью за выбор и опасностью превратить собственную волю в право переступать через другого.</p>"},guilt:{title:"Вина",body:"<p>Вина может быть юридической, нравственной и внутренней — эти уровни не всегда совпадают.</p>"},faith:{title:"Вера и сомнение",body:"<p>Герои спорят, сомневаются и требуют доказательств; религиозная проблематика почти всегда связана с драмой выбора.</p>"},other:{title:"Другой человек",body:"<p>Унижение, сострадание, любовь и власть показывают, насколько трудно увидеть в другом самостоятельную личность.</p>"},beauty:{title:"«Красота спасет мир»",body:"<p>Фраза произносится князем Мышкиным в «Идиоте» и требует чтения внутри романа, а не превращения в лозунг.</p>"}};
function setupModal(){const modal=q("[data-modal-root]");if(!modal)return;const title=q("[data-modal-title]",modal),body=q("[data-modal-body]",modal);const close=()=>{modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")};const open=d=>{title.textContent=d.title;body.innerHTML=d.body;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");q(".modal-close",modal)?.focus()};qa("[data-modal]").forEach(b=>b.addEventListener("click",()=>{const d=modalData[b.dataset.modal];if(d)open(d)}));qa("[data-modal-close]",modal).forEach(b=>b.addEventListener("click",close));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("open"))close()})}
const timelineData={1821:["Рождение в Москве","11 ноября 1821 года по новому стилю Фёдор Михайлович родился в Москве."],1846:["«Бедные люди»","В 1846 году опубликован первый роман Достоевского."],1849:["Арест и инсценировка казни","В апреле Достоевский был арестован по делу петрашевцев; в декабре смертный приговор был отменён перед исполнением."],1866:["«Преступление и наказание»","В 1866 году началась журнальная публикация романа."],1879:["«Братья Карамазовы»","Последний роман выходил в 1879–1880 годах."],1881:["Последняя глава","Достоевский умер 9 февраля 1881 года по новому стилю в Петербурге."]};
function setupTimeline(){const card=q("[data-timeline-card]");if(!card)return;const render=y=>{const d=timelineData[y];if(!d)return;card.innerHTML='<span class="year">'+y+'</span><h3>'+d[0]+'</h3><p>'+d[1]+'</p>';qa(".timeline-item").forEach(x=>x.classList.toggle("active",x.dataset.year===String(y)))};qa(".timeline-item").forEach(b=>b.addEventListener("click",()=>render(b.dataset.year)));render(1821)}
function setupQuiz(){const root=q("[data-quiz]");if(!root)return;const questions=[["В каком году родился Достоевский?",["1812","1821","1831","1841"],1],["Какое произведение принесло первый большой успех?",["«Идиот»","«Бесы»","«Бедные люди»","«Игрок»"],2],["Сколько лет каторги он получил?",["2","4","6","8"],1],["Какой роман стал последним?",["«Братья Карамазовы»","«Подросток»","«Бесы»","«Идиот»"],0],["Где мемориальная квартира в Петербурге?",["Невский проспект","Кузнечный переулок","Литейный проспект","Васильевский остров"],1]];const question=q("[data-question]",root),bar=q("[data-progress]",root),next=q("[data-next]",root),scoreEl=q("[data-score]",root);let i=0,score=0,selected=null;const render=()=>{const x=questions[i];bar.style.width=((i+1)/questions.length*100)+"%";question.innerHTML='<div class="quiz-question">'+(i+1)+'. '+x[0]+'</div><div class="answers">'+x[1].map((a,n)=>'<button class="answer" data-answer="'+n+'">'+a+'</button>').join("")+'</div>';selected=null;next.disabled=true;qa(".answer",root).forEach(b=>b.addEventListener("click",()=>{qa(".answer",root).forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selected=Number(b.dataset.answer);next.disabled=false}))};next.addEventListener("click",()=>{if(i>=questions.length){i=0;score=0;next.textContent="Ответить";render();return}if(selected===null)return;if(selected===questions[i][2])score++;i++;if(i<questions.length){next.textContent=i===questions.length-1?"Завершить":"Ответить";render()}else{question.innerHTML='<div class="quiz-question">Готово. Ваш результат — '+score+' из '+questions.length+'.</div><p>'+(score>=4?"Отличный результат.":"Хорошее начало. Пройдите хронологию ещё раз.")+'</p>';next.textContent="Пройти ещё раз";next.disabled=false}});render()}
const oldBoot=document.querySelector("body");document.addEventListener("DOMContentLoaded",()=>{setupModal();setupTimeline();setupQuiz()});
(function(){document.addEventListener("DOMContentLoaded",function(){var p=location.pathname.toLowerCase();var map=[["biography","page-biography"],["chronology","page-chronology"],["works","page-works"],["ideas","page-ideas"],["petersburg","page-petersburg"],["family","page-family"],["gallery","page-gallery"],["research","page-research"],["sources","page-sources"],["index","page-home"]];var b=document.body;map.forEach(function(x){if(p.indexOf(x[0])>-1)b.classList.add(x[1])});document.querySelectorAll(".page-hero,.page-cinema,.section,.section-paper,.dossier,.context-card,.gallery-item,.reading-item").forEach(function(el){el.classList.add("reveal")});var io="IntersectionObserver" in window?new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add("is-visible");io.unobserve(e.target)}})} ,{threshold:.08}):null;if(io)document.querySelectorAll(".reveal").forEach(function(e){io.observe(e)})})})();