(()=>{"use strict";
const q=(selector,root=document)=>root.querySelector(selector);
const qa=(selector,root=document)=>[...root.querySelectorAll(selector)];
const header=q("[data-header]");
const progress=q("[data-progress]");
function updateScrollState(){const scrollTop=window.scrollY;header?.classList.toggle("scrolled",scrollTop>30);if(progress){const scrollable=document.documentElement.scrollHeight-window.innerHeight;const percent=scrollable>0?(scrollTop/scrollable)*100:0;progress.style.width=`${Math.min(100,Math.max(0,percent))}%`;}}
window.addEventListener("scroll",updateScrollState,{passive:true});updateScrollState();
const menuButton=q("[data-menu]");
menuButton?.addEventListener("click",()=>{const isOpen=header?.classList.toggle("menu-open")??false;menuButton.setAttribute("aria-expanded",String(isOpen));menuButton.setAttribute("aria-label",isOpen?"Закрыть меню":"Открыть меню");});
qa(".nav a").forEach((link)=>{if(link.href===window.location.href)link.classList.add("active");link.addEventListener("click",()=>{header?.classList.remove("menu-open");menuButton?.setAttribute("aria-expanded","false");menuButton?.setAttribute("aria-label","Открыть меню");});});
document.addEventListener("keydown",(event)=>{if(event.key==="Escape"&&header?.classList.contains("menu-open")){header.classList.remove("menu-open");menuButton?.setAttribute("aria-expanded","false");menuButton?.setAttribute("aria-label","Открыть меню");menuButton?.focus();}});
const revealObserver="IntersectionObserver"in window?new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add("visible");revealObserver.unobserve(entry.target);}}),{threshold:.08}):null;
const observeReveal=()=>qa(".reveal").forEach((element)=>revealObserver?revealObserver.observe(element):element.classList.add("visible"));
qa(".reveal").forEach((element)=>revealObserver?revealObserver.observe(element):element.classList.add("visible"));
const cursor=q("[data-cursor]");if(cursor&&window.matchMedia("(pointer:fine)").matches)window.addEventListener("pointermove",(event)=>{cursor.style.left=`${event.clientX}px`;cursor.style.top=`${event.clientY}px`;},{passive:true});
qa(".library-card").forEach((card,index)=>{card.style.transitionDelay=`${Math.min(index%3*45,90)}ms`;});
const filterButtons=qa("[data-filter]");const filterItems=qa("[data-filter-item]");const filterCount=q("[data-count]");
function applyFilter(value){let visible=0;filterItems.forEach((item)=>{const categories=(item.dataset.filterItem||"").split(/\s+/).filter(Boolean);const shouldShow=value==="all"||categories.includes(value);item.hidden=!shouldShow;if(shouldShow)visible++;});if(filterCount)filterCount.textContent=`${visible} материалов`;filterButtons.forEach((button)=>button.classList.toggle("active",button.dataset.filter===value));}
if(filterButtons.length){applyFilter("all");filterButtons.forEach((button)=>button.addEventListener("click",()=>applyFilter(button.dataset.filter||"all")));}
const modalData={freedom:{title:"Свобода",body:"<p>У Достоевского свобода связана с ответственностью за выбор и опасностью превратить собственную волю в право переступать через другого.</p>"},guilt:{title:"Вина",body:"<p>Вина может быть юридической, нравственной и внутренней — эти уровни не всегда совпадают.</p>"},faith:{title:"Вера и сомнение",body:"<p>Герои спорят, сомневаются и требуют доказательств; религиозная проблематика почти всегда связана с драмой выбора.</p>"},other:{title:"Другой человек",body:"<p>Унижение, сострадание, любовь и власть показывают, насколько трудно увидеть в другом самостоятельную личность.</p>"},beauty:{title:"«Красота спасет мир»",body:"<p>Фраза связана с князем Мышкиным в «Идиоте» и требует чтения внутри романа, а не превращения в лозунг.</p>"}};
function setupModal(){const modal=q("[data-modal-root]");if(!modal)return;const title=q("[data-modal-title]",modal);const body=q("[data-modal-body]",modal);const close=()=>{modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");};qa("[data-modal]",document).forEach((button)=>button.addEventListener("click",()=>{const data=modalData[button.dataset.modal];if(!data)return;title.textContent=data.title;body.innerHTML=data.body;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");q(".modal-close",modal)?.focus();}));qa("[data-modal-close]",modal).forEach((button)=>button.addEventListener("click",close));modal.addEventListener("click",(event)=>{if(event.target===modal)close();});document.addEventListener("keydown",(event)=>{if(event.key==="Escape"&&modal.classList.contains("open"))close();});}
const timelineData={1821:["Рождение в Москве","11 ноября 1821 года по новому стилю Фёдор Михайлович родился в Москве."],1846:["«Бедные люди»","В 1846 году опубликован первый роман Достоевского."],1849:["Арест и инсценировка казни","В апреле Достоевский был арестован по делу петрашевцев; в декабре смертный приговор был отменён перед исполнением."],1866:["«Преступление и наказание»","В 1866 году началась журнальная публикация романа."],1879:["«Братья Карамазовы»","Последний роман выходил в 1879–1880 годах."],1881:["Последняя глава","Достоевский умер 9 февраля 1881 года по новому стилю в Петербурге."]};
function setupTimeline(){const card=q("[data-timeline-card]");if(!card)return;const render=(year)=>{const data=timelineData[year];if(!data)return;card.innerHTML=`<span class="year">${year}</span><h3>${data[0]}</h3><p>${data[1]}</p>`;qa(".timeline-item").forEach((item)=>item.classList.toggle("active",item.dataset.year===String(year)));};qa(".timeline-item").forEach((button)=>button.addEventListener("click",()=>render(button.dataset.year)));render(1821);}
function setupQuiz(){const root=q("[data-quiz]");if(!root)return;const questions=[["В каком году родился Достоевский?",["1812","1821","1831","1841"],1],["Какое произведение принесло первый большой успех?",["«Идиот»","«Бесы»","«Бедные люди»","«Игрок»"],2],["Сколько лет каторги он получил?",["2","4","6","8"],1],["Какой роман стал последним?",["«Братья Карамазовы»","«Подросток»","«Бесы»","«Идиот»"],0],["Где находится мемориальная квартира в Петербурге?",["Невский проспект","Кузнечный переулок","Литейный проспект","Васильевский остров"],1]];const question=q("[data-question]",root);const progressBar=q("[data-progress]",root);const nextButton=q("[data-next]",root);let index=0;let score=0;let selected=null;const render=()=>{const current=questions[index];progressBar.style.width=`${((index+1)/questions.length)*100}%`;question.innerHTML=`<div class="quiz-question">${index+1}. ${current[0]}</div><div class="answers">${current[1].map((answer,n)=>`<button class="answer" type="button" data-answer="${n}">${answer}</button>`).join("")}</div>`;selected=null;nextButton.disabled=true;qa(".answer",root).forEach((button)=>button.addEventListener("click",()=>{qa(".answer",root).forEach((item)=>item.classList.remove("selected"));button.classList.add("selected");selected=Number(button.dataset.answer);nextButton.disabled=false;}));};nextButton.addEventListener("click",()=>{if(selected===null)return;if(selected===questions[index][2])score++;index++;if(index<questions.length){nextButton.textContent=index===questions.length-1?"Завершить":"Ответить";render();return;}question.innerHTML=`<div class="quiz-question">Готово. Ваш результат — ${score} из ${questions.length}.</div><p>${score>=4?"Отличный результат.":"Хорошее начало. Пройдите хронологию ещё раз."}</p>`;nextButton.textContent="Пройти ещё раз";nextButton.disabled=false;progressBar.style.width="100%";index=-1;});nextButton.addEventListener("click",()=>{if(index===-1){index=0;score=0;nextButton.textContent="Ответить";render();}});render();}
function setPageClass(){const file=window.location.pathname.split("/").pop().toLowerCase();const page=file.endsWith(".html")?file.slice(0,-5):file;const map={"":"page-home",index:"page-home",biography:"page-biography",chronology:"page-chronology",works:"page-works",ideas:"page-ideas",petersburg:"page-petersburg",family:"page-family",gallery:"page-gallery",research:"page-research",sources:"page-sources"};if(map[page])document.body.classList.add(map[page]);}
document.addEventListener("DOMContentLoaded",()=>{setPageClass();qa(".page-hero,.page-cinema,.section,.section-paper,.dossier,.context-card,.gallery-item,.reading-item").forEach((element)=>element.classList.add("reveal"));observeReveal();setupModal();setupTimeline();setupQuiz();});
})();